/**
 * @deprecated Import from `@main/agent/sandbox` instead.
 * Re-export for skill tool bundles.
 */
export {
  TERALEXI_AGENT_SANDBOX_ROOT_ENV,
  SANDBOX_ROOT_GLOBAL_KEY,
  TERALEXI_AGENT_SANDBOX_OUTPUT_SCOPE_ENV,
  SANDBOX_OUTPUT_SCOPE_GLOBAL_KEY,
  TERALEXI_AGENT_WORKSPACE_PATH_ENV,
  WORKSPACE_PATH_GLOBAL_KEY,
  ensureToolLoopStepOutputDirs,
  getOutputResultsRelPrefix,
  getOutputScriptsRelPrefix,
  getSandboxOutputScopeFromEnv,
  remapLegacyPlanRelativePath,
  remapLegacySharedOutputPath,
  setSandboxOutputScope,
  toolLoopOutputRelBase,
  defaultToolLoopPreviewDir,
  getSandboxRootFromEnv,
  requireActiveSandbox,
  isPathInsideSandbox,
  isPathInsideWorkspace,
  resolveSandboxRelativePath,
  resolveScopedSandboxPath,
  resolvePathMustBeInside,
  resolvePathAllowingOutside,
  assertMoveAllowed,
  sandboxPathError,
  getWorkspacePathFromEnv,
  getConversationIdFromEnv,
  resolvePathInContext,
  resolveScopedPathInContext,
  isPathInFilesystemContext,
  isSandboxArtifactRelativePath,
  isPseudoAbsoluteProjectPath,
  resolveUserProjectPath,
} from '@main/agent/sandbox'
