import { existsSync, readdirSync, readFileSync, writeFileSync } from 'node:fs'
import { join } from 'node:path'
import { isLoadableExtensionFolder } from '../src/main/skills/skill-path'

const EXTENSIONS_ROOT = join(process.cwd(), 'extensions')
const OUT_FILE = join(process.cwd(), 'src/main/skills/bundled-extensions.generated.ts')

type GeneratedExtension = {
  id: string
  manifestJson: string
}

function emit(extensions: GeneratedExtension[]): void {
  const body = extensions
    .map(
      (ext) => `  ${JSON.stringify(ext.id)}: ${JSON.stringify(ext.manifestJson)},`,
    )
    .join('\n')

  const source = `/** Generated by .electron-vite/generate-bundled-extensions.ts — do not edit. */

export const BUNDLED_EXTENSION_MANIFESTS: Record<string, string> = {
${body}
}

export function getBundledExtensionIds(): string[] {
  return Object.keys(BUNDLED_EXTENSION_MANIFESTS)
}

export function isBundledExtensionId(id: string): boolean {
  return id in BUNDLED_EXTENSION_MANIFESTS
}
`
  writeFileSync(OUT_FILE, source, 'utf-8')
}

export function generateBundledExtensionsManifest(): void {
  if (!existsSync(EXTENSIONS_ROOT)) {
    emit([])
    return
  }
  const out: GeneratedExtension[] = []
  for (const entry of readdirSync(EXTENSIONS_ROOT)) {
    if (!isLoadableExtensionFolder(EXTENSIONS_ROOT, entry)) continue
    const manifestPath = join(EXTENSIONS_ROOT, entry, 'extension.json')
    out.push({
      id: entry,
      manifestJson: readFileSync(manifestPath, 'utf-8'),
    })
  }
  emit(out.sort((a, b) => a.id.localeCompare(b.id)))
}

if (import.meta.url === `file://${process.argv[1]}`) {
  generateBundledExtensionsManifest()
  console.log(`Wrote bundled extensions to ${OUT_FILE}`)
}
