app.build.hotPublishConfigName=update-config
app.build.hotPublishUrl=
app.dev.chineseLog=false
app.dev.port=9080
app.dev.removeElectronJunk=true
app.google.clientId=
app.google.clientSecret=
app.paths.dllFolder=
app.paths.hotUpdateFolder=update
app.window.useStartupChart=true
app.window.useSystemTitle=false
settings.whatsapp.ackMessage=Received. Thanks for your message.
