/** Generated by .electron-vite/generate-bundled-extensions.ts — do not edit. */

export const BUNDLED_EXTENSION_MANIFESTS: Record<string, string> = {
  "demo-channel": "{\n  \"id\": \"demo-channel\",\n  \"version\": \"1.0.0\",\n  \"permissions\": {\n    \"filesystem\": \"workspace\",\n    \"network\": false,\n    \"shell\": false\n  },\n  \"activationEvents\": [\"onStartup\"]\n}\n",
  "demo-llm": "{\n  \"id\": \"demo-llm\",\n  \"version\": \"1.0.0\",\n  \"permissions\": {\n    \"network\": true\n  }\n}\n",
  "hook-judge": "{\n  \"id\": \"hook-judge\",\n  \"version\": \"1.0.0\",\n  \"permissions\": {\n    \"filesystem\": \"workspace\",\n    \"network\": true,\n    \"shell\": false\n  },\n  \"contributes\": {\n    \"hooks\": {\n      \"onApprovalRequired\": [\n        {\n          \"type\": \"prompt\",\n          \"prompt\": \"You are a security reviewer. If the tool call looks destructive or reads secrets, reply with {\\\"continue\\\":false,\\\"stopReason\\\":\\\"Blocked by hook-judge\\\"}. Otherwise reply with {\\\"continue\\\":true}.\",\n          \"model\": \"openai:gpt-4o-mini\"\n        }\n      ]\n    }\n  }\n}\n",
  "secret-guard": "{\n  \"id\": \"secret-guard\",\n  \"version\": \"1.0.0\",\n  \"permissions\": {\n    \"filesystem\": \"workspace\",\n    \"shell\": false,\n    \"network\": false\n  }\n}\n",
}

export function getBundledExtensionIds(): string[] {
  return Object.keys(BUNDLED_EXTENSION_MANIFESTS)
}

export function isBundledExtensionId(id: string): boolean {
  return id in BUNDLED_EXTENSION_MANIFESTS
}
